Portuguese translation
ollo69/ha-smartthinq-sensors pull request #113
Opened 2020-12-13 20:14 UTC by fnasciment0

Portuguese translation

2020-12-13 20:53 UTC, ollo69 requested changes

2020-12-13 20:53 UTC, ollo69 commented on custom_components/smartthinq_sensors/translations/pt.json
> +            "invalid_url": "URL de redirecionamento inválido.",
Can you enrich this translation as already done for `en.json` and `it.json`

2020-12-13 20:53 UTC, ollo69 commented on custom_components/smartthinq_sensors/.translations/pt.json
> +            "invalid_url": "URL de redirecionamento inválido.",
Can you enrich this translation as already done for `en.json` and `it.json`

2020-12-14 22:53 UTC, ollo69 approved these changes

2020-12-14 22:54 UTC, merged

2021-06-09 02:23 UTC, beped commented
Hi, how can i use the translation inside the HACS? i didnt find on the instructions.