Add support for getting air purifier's top filter life
ollo69/ha-smartthinq-sensors pull request #217
Opened 2021-10-01 16:13 UTC by rain931215

The community reported that some models have two filters, so I implemented it into the repo.
![244011257_924021984859279_3985432566047979537_n](https://user-images.githubusercontent.com/35858349/135652669-76a94d2f-d976-4280-9e7e-6365d36f221f.png)
![243476557_149366407337340_6591584959245992625_n](https://user-images.githubusercontent.com/35858349/135652682-f55998ec-4e10-4732-ad90-63d3573fe7aa.jpg)

2021-10-02 13:19 UTC, ollo69 commented
You should implement filter as `features` to determinate if is available or not. Look at `washerDryer` as example. You should probably calculate percentage directly in API instead of returning 2 values and calculate in HA.

2021-10-02 15:26 UTC, ollo69 requested changes
See my comment above

2021-10-03 15:30 UTC, ollo69 requested changes

2021-10-03 15:30 UTC, ollo69 commented on custom_components/smartthinq_sensors/wideq/airpurifier.py
> +        max_time = self._data.get(self._get_state_key(AIR_PURIFIER_STATE_FILTERMNG_MAX_TIME))
Looks good, just avoid trying operation if `use_time` is `None` (that probably means filter not exist) and return immediately `None` in case.

2021-10-03 15:30 UTC, ollo69 commented on custom_components/smartthinq_sensors/wideq/airpurifier.py
> +        max_time = self._data.get(self._get_state_key(AIR_PURIFIER_STATE_FILTERMNG_MAX_TIME_TOP))
Same as comment above

2021-10-03 21:48 UTC, ollo69 commented
I commit some changes in `AirPurifierStatus` directly in this PR, could you take a look and check that everything works properly with your device?

2021-10-04 14:10 UTC, rain931215 commented
The upper filter's use time and max time value is always exist even if the device doesn't have that filter
so your commit makes the filter detection not work.
I detect the filter by checking if "@SUPPORT_D_PLUS_TOP" is in "support.mFilter"

2021-10-04 14:27 UTC, ollo69 commented
Understood. So let's restore your check and verify that everything is working properly with my others changes, that make the class more compliant with others.

2021-10-04 14:49 UTC, rain931215 commented
It works fine now.

2021-10-04 19:52 UTC, ollo69 approved these changes

2021-10-04 19:53 UTC, merged