Create Danish translation
ollo69/ha-smartthinq-sensors pull request #500
Opened 2023-02-17 12:29 UTC by greew

Thank you for a great integration.

I've added a Danish translation.

2023-03-12 07:58 UTC, RaMin0 requested changes

2023-03-12 07:58 UTC, RaMin0 commented on custom_components/smartthinq_sensors/translations/da.json
> +            "no_smartthinq_devices": "Der blev ikke fundet nogetn SmartThinQ enheder. Komponent-setup annulleres.",
```suggestion
            "no_smartthinq_devices": "Der blev ikke fundet nogen SmartThinQ enheder. Komponent-setup annulleres.",
```

2023-03-12 10:09 UTC, RaMin0 approved these changes

2023-11-01 21:53 UTC, ollo69 approved these changes

2023-11-01 21:54 UTC, ollo69 commented
Thanks👍

2023-11-01 21:55 UTC, merged