First microwave support
ollo69/ha-smartthinq-sensors pull request #566
Opened 2023-06-20 00:59 UTC by titilambert

Hello !

This is my first contribution to this cool project !

I'm trying to add microwave support.
I still miss microwave status (cooking state /cook time left/...) but I'm able to set different settings like: time/sound/weight/light/...

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/47721/f78c3f01-81ff-4f72-89c8-5a1db00de256)

This PR tries to fix https://github.com/ollo69/ha-smartthinq-sensors/issues/385

Please feel free to change my code to make it mode similar to the base code :)

2023-06-21 19:11 UTC, samuelkadolph commented
Following as I recently got an LG ThinQ microwave. I can try to test it out on the weekend.

Also not sure if it's exposed via the API but there's an additional setting for the turntable on/off. You can set it on the microwave itself but not in the ThinQ app so it might not be exposed.

2023-06-23 23:42 UTC, samuelkadolph commented
Got it set up and working with my microwave. First observations:

* Turning Clock 24h format on seems to just clear the clock. I see that option is gone from my ThinQ app (it was there last weekend)
* Light has a low and high setting not present in this integration
* I think the weight units should be a dropdown with lbs/kgs instead of a toggle
* App has night light setting, possible to implement?
* App has timer icon in top left for 'oven' timer, I don't think it's worth implementing in HA
* Cooking features, do you want to implement? I see there's microwave/defrost/timed defrost modes, cook time, power strength and 'Send' to start the cook

2023-06-23 23:44 UTC, TheAlphaLaw commented
> Got it set up and working with my microwave. First observations:
> 
> * Turning Clock 24h format on seems to just clear the clock. I see that option is gone from my ThinQ app (it was there last weekend)
> * Light has a low and high setting not present in this integration
> * I think the weight units should be a dropdown with lbs/kgs instead of a toggle
> * App has night light setting, possible to implement?
> * App has timer icon in top left for 'oven' timer, I don't think it's worth implementing in HA
> * Cooking features, do you want to implement? I see there's microwave/defrost/timed defrost modes, cook time, power strength and 'Send' to start the cook

Just FYI on cook time, it can only add time to an already cooking microwave but not start a new cook.

2023-06-24 00:51 UTC, samuelkadolph commented
> Just FYI on cook time, it can only add time to an already cooking microwave but not start a new cook.

That's not what I'm seeing with the ThinQ. You pick the settings you want and press 'Send'. It sends them over to the microwave. Then you have to press start. When it's running, the app only shows the status and you can't change it.

2023-06-24 13:00 UTC, ollo69 requested changes
Thank you very match for this PR. Please take a look to my review comments.

2023-06-25 19:43 UTC, samuelkadolph commented
24 hour time select still just turns the clock (if off) and sets it to 12:00 AM. The setting is gone from the ThinQ app so I don't think it's a thing anymore? I installed my new ThinQ range this weekend and it does have a (working) 24 hour clock setting. Annoying they aren't consistent.

2023-07-01 01:19 UTC, titilambert commented on custom_components/smartthinq_sensors/wideq/factory.py
> +        return [MicroWaveDevice(client, device_info)]
fixed

2023-07-01 01:19 UTC, titilambert commented on custom_components/smartthinq_sensors/wideq/factory.py
> +from .devices.microwave import MicroWaveDevice
fixed

2023-07-01 01:19 UTC, titilambert commented on custom_components/smartthinq_sensors/wideq/const.py
> +    VENT_SPEED = "vent_speed"
fixed

2023-07-01 01:19 UTC, titilambert commented on custom_components/smartthinq_sensors/__init__.py
> +    Platform.SELECT,
fixed

2023-07-01 01:20 UTC, titilambert commented on custom_components/smartthinq_sensors/__init__.py
> +        _LOGGER.debug("Updating ThinQ device %s", self._name)
fixed

2023-07-01 08:02 UTC, ollo69 commented
@titilambert, any news on changes requested?

2023-07-02 00:56 UTC, titilambert commented
> @titilambert, any news on changes requested?

I fixed the easy ones, Trying now to improve the set_time services as suggested.
I don't understand which wash service should I "copy"

2023-07-02 01:45 UTC, titilambert commented on custom_components/smartthinq_sensors/services.yaml
> +            model: WMVEL2137-MicrowaveOven (MICROWAVE)
fixed

2023-07-02 01:46 UTC, titilambert commented on custom_components/smartthinq_sensors/__init__.py
> +        )
fixed

2023-07-02 01:46 UTC, titilambert commented
@ollo69 I finally got the service done as suggested.
I will try to fix the last two comment in few the days

2023-07-03 00:14 UTC, samuelkadolph commented
Updating to the latest (8012b34) removes my microwave from HASS. I have the MVEL2033F. Shows up as WMVEL2137 from the LG API. I'll upload my diagnostics file for the microwave.

[smartthinq_sensors-33e935dee672f618b22a784d3e770f66-Microwave-a0ef3857fc07022ae5c09b1957ec8ba4.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11931817/smartthinq_sensors-33e935dee672f618b22a784d3e770f66-Microwave-a0ef3857fc07022ae5c09b1957ec8ba4.json.txt)

2023-07-09 17:25 UTC, ollo69 requested changes

2023-07-09 17:25 UTC, ollo69 commented on custom_components/smartthinq_sensors/device_helpers.py
> +        super().__init__(api_device)
This is useless, there are no dedicated method. Just use `LGEBaseDevice`.

2023-07-09 17:25 UTC, ollo69 commented on custom_components/smartthinq_sensors/__init__.py
> +
I think this is not used anymore

2023-07-09 17:28 UTC, ollo69 requested changes

2023-07-09 17:28 UTC, ollo69 commented on custom_components/smartthinq_sensors/sensor.py
> +        return data
I think also this is useless, `LGESensor` should already implement this logic for `DEFAULT_SENSOR`

2023-07-09 17:32 UTC, ollo69 commented
Please take a look to failing `Linting` test.

2023-07-14 07:37 UTC, ollo69 commented
@titilambert,

when do you think you will be able to complete this PR? I would make some changes to codebase to respect last HA changes but this will create conflict with PR, so should be better to merge before.

2023-07-15 00:08 UTC, titilambert commented
> @titilambert,
> 
> when do you think you will be able to complete this PR? I would make some changes to codebase to respect last HA changes but this will create conflict with PR, so should be better to merge before.

Hello, I do not know when I will be able to achieve it I don't have a lot of time, and I'm stuck with Fan state :/

Can you merge it then disable the microwave ?
I can continue after your changes.

Thanks !

2023-07-15 00:09 UTC, titilambert commented
> @titilambert,
> 
> when do you think you will be able to complete this PR? I would make some changes to codebase to respect last HA changes but this will create conflict with PR, so should be better to merge before.

Hello @ollo69, I do not know when I will be able to achieve it ... I don't have a lot of time, and I'm stuck with Fan status :/

Can you merge it then disable the microwave ?
I can continue after your changes.

Thanks !

2023-07-31 04:27 UTC, trentjw commented
any progress on this I have a over the range microwave that is waiting to find its way into home assistant thanks

2023-08-03 16:55 UTC, teek541 commented
I yoo am interested in this.  Would ve nice to set timers through HA and control automations with it.

2023-08-07 16:53 UTC, trentjw commented
well the model number of my microwave is MHEC1737D if that makes any difference though this seems to have lost momentum

2023-08-07 17:00 UTC, teek541 commented
I have the same one!  Just a different color. lol

2023-08-07 17:32 UTC, trentjw commented
you got the MHEC1737F one eh?

2023-08-07 17:48 UTC, ollo69 commented
All, 

I'm currently working on this PR, but it require times. Please be patient.

2023-08-14 13:54 UTC, teek541 commented
Thanks for the update, I'll do a test.  My network switch just bricked itself last night so I'm waiting on my replacement first.

2023-08-14 15:30 UTC, trentjw commented
> Thanks for the update, I'll do a test. My network switch just bricked itself last night so I'm waiting on my replacement first.

its not uploaded yet so if it is then it does not work

2023-08-14 15:47 UTC, ollo69 commented
> its not uploaded yet so if it is then it does not work

What do you mean? This PR is still not merged, to test this you must update your installation with this branch.

2023-08-14 20:05 UTC, TheAlphaLaw commented
> > Thanks for the update, I'll do a test. My network switch just bricked itself last night so I'm waiting on my replacement first.
> 
> its not uploaded yet so if it is then it does not work

@trentjw Sounds like you may not be familiar with Github or how Home Assistant operates as an open source platform. If you're not pulling code to test manually, then I advise that you be patient and wait for the PR to be merged and Home Assitant updated. ollo69 is doing this in his free time in an effort to help the community.

2023-08-14 20:55 UTC, trentjw commented
> > > Thanks for the update, I'll do a test. My network switch just bricked itself last night so I'm waiting on my replacement first.
> > 
> > 
> > its not uploaded yet so if it is then it does not work
> 
> @trentjw Sounds like you may not be familiar with Github or how Home Assistant operates as an open source platform. If you're not pulling code to test manually, then I advise that you be patient and wait for the PR to be merged and Home Assitant updated. ollo69 is doing this in his free time in an effort to help the community.

always one in the crowd that has to inject themselves and offer nothing

2023-08-14 22:00 UTC, teek541 commented
> > > Thanks for the update, I'll do a test. My network switch just bricked itself last night so I'm waiting on my replacement first.
> > 
> > 
> > its not uploaded yet so if it is then it does not work
> 
> @trentjw Sounds like you may not be familiar with Github or how Home Assistant operates as an open source platform. If you're not pulling code to test manually, then I advise that you be patient and wait for the PR to be merged and Home Assitant updated. ollo69 is doing this in his free time in an effort to help the community.

Might I suggest you tell us how to do that as I too am new and assumed that this would have shown up as an update for me to install when I got home and got a new working switch installed? :-D  Do I just use this as a new custom repository?

2023-08-14 23:28 UTC, zimmra commented
@ollo69 

In attempt to get this discussion back on track to this PR...

Here are my findings with the current PR code

I deleted the SmartThinq LGE Sensors integration from Home Asssistant
I shutdown Home Assistant then deleted my existing smartthinq_sensors folder and then fetched/checked out this PR
I then started my Home Assistant instance, and then re-added the integration as a new integration
I'm not home to test the sensor states, but am able to test everything else

## Fan Entity

- Vent entity shows up, but looks like it is unavailable. 
	- Changing the Vent Speed in the app has no effect on this
	- ![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/28514085/5effb06c-4587-4d1d-addf-51218fa5341f)
- Light entity does not show up at all

## Configuration Switch/Select Entities

- These all populate and do set the specific config setting on the microwave**
- **Only the config entity you change is set, then everything else goes to a default value
	- if anything other than `Clock Display` is changed, `Clock Display` changes to `On`/`Show`
	- If anything other than `Display Scroll Speed` is changed, `Display Scroll Speed` changes to `Slow`
	- If anything other than `Sound` is changed, `Sound` is changed to `Off`
	- If anything other than `Weight Unit` is changed, `Weight Unit` changes to `KG`
- For example, if I change `Weight Unit` to `LB` the setting is reflected in the app correctly, but then the 3 other applicable config entities get changed to the default value listed above
- ![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/28514085/7ab067c5-2be0-4782-ba02-ae3542eafc2c)

## Sensor Entites
- I am unable to test the sensor entities below until I am home with the unit
	- sensor.microwave, sensor.microwave_oven_mode, sensor.microwave_oven_state

2023-08-15 12:58 UTC, ollo69 commented
> Might I suggest you tell us how to do that as I too am new and assumed that this would have shown up as an update for me to install when I got home and got a new working switch installed? :-D Do I just use this as a new custom repository?

@teek541,

until this PR is not merged, the only way to test this is to manually install integration taking the code from this branch. This is not so simple as install from HACS and if you don't have experience it will be simple to make mistake. I you don want to take risk, just wait for tests finish and new release available.

2023-08-15 15:44 UTC, ollo69 commented
> On an Over-The-Range Microwave, you use the vent when the range (stove) below is in use

So the vent can be always turned on or there are some condition when it is not possible?

> I could be mistaken, but I thought I read on the LG api documentation that it is expecting all of them to be sent

I will try to change implementation to always send all values, anyway doesn't seems a good approach always set time. It would be good if you will be able to do a mitm

2023-08-15 17:07 UTC, ollo69 commented
Ok, I implemented some changes based on test results, please try again and give me your feedback

2023-08-15 22:58 UTC, zimmra commented
I got mitm proxy setup today
**It appears settings are all set even when individual setting is changed**

Here's what I've poked in to so far, I think this should be conclusive enough - but let me know if you want any other information @ollo69 

I will also try out your changes

## Turned vent on (direct to Low) in app

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 0,
            "mwoLampOnOff": "DISABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 1
        }
    },
    "dataValue": null
}
```

## Turned Light On (direct to low) in App

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 1,
            "mwoLampOnOff": "ENABLE",
            "mwoVentOnOff": "DISABLE",
            "mwoVentSpeedLevel": 0
        }
    },
    "dataValue": null
}
```

## Turned clock from Show -> Hide in app

```json
{
    "command": "Set",
    "ctrlKey": "SetPreference",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_SETTING",
            "cmdOptionDataLength": "REMOTE_SETTING",
            "mwoSettingClockDisplay": "CLOCK_HIDE",
            "mwoSettingClockSetHourMode": "NOT_SET",
            "mwoSettingClockSetTimeHour": 128,
            "mwoSettingClockSetTimeMin": 128,
            "mwoSettingClockSetTimeSec": 128,
            "mwoSettingDefrostWeightMode": "NOT_SET",
            "mwoSettingDemoMode": "NOT_SET",
            "mwoSettingDisplayScrollSpeed": "NOT_SET",
            "mwoSettingSound": "NOT_SET"
        }
    },
    "dataValue": null
}
```

## Turned clock from Hide -> Show in app

```json
{
    "command": "Set",
    "ctrlKey": "SetPreference",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_SETTING",
            "cmdOptionDataLength": "REMOTE_SETTING",
            "mwoSettingClockDisplay": "CLOCK_SHOW",
            "mwoSettingClockSetHourMode": "NOT_SET",
            "mwoSettingClockSetTimeHour": 128,
            "mwoSettingClockSetTimeMin": 128,
            "mwoSettingClockSetTimeSec": 128,
            "mwoSettingDefrostWeightMode": "NOT_SET",
            "mwoSettingDemoMode": "NOT_SET",
            "mwoSettingDisplayScrollSpeed": "NOT_SET",
            "mwoSettingSound": "NOT_SET"
        }
    },
    "dataValue": null
}
```

## Set clock time in app

```json
{
    "command": "Set",
    "ctrlKey": "SetPreference",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_SETTING",
            "cmdOptionDataLength": "REMOTE_SETTING",
            "mwoSettingClockDisplay": "NOT_SET",
            "mwoSettingClockSetHourMode": "NOT_SET",
            "mwoSettingClockSetTimeHour": 15,
            "mwoSettingClockSetTimeMin": 55,
            "mwoSettingClockSetTimeSec": 24,
            "mwoSettingDefrostWeightMode": "NOT_SET",
            "mwoSettingDemoMode": "NOT_SET",
            "mwoSettingDisplayScrollSpeed": "NOT_SET",
            "mwoSettingSound": "NOT_SET"
        }
    },
    "dataValue": null
}
```

2023-08-15 23:12 UTC, ollo69 commented
> I got mitm proxy setup today

Great, this is really useful.

I suggest to wait that I align the code with discovered commands before trying my last changes, now is clear to me how to properly manage preference.

Thanks a lot.

2023-08-15 23:17 UTC, zimmra commented
> > I got mitm proxy setup today
> 
> Great, this is really useful.
> 
> I suggest to wait that I align the code with discovered commands before trying my last changes, now is clear to me how to properly manage preference.
> 
> Thanks a lot.

Glad to help!

I just updated my comment to add a few more entries (most notably `Timer`, but also cook time and defrost info), as well as made it collapsible to make the discussion page here a bit more managable. 

Please let me know if there's anything I can pull from it for you, though I think I covered the main control functions.  

Thanks again for the hard work!

2023-08-15 23:49 UTC, ollo69 commented
@zimmra,

could you please make a last test? What is the command sent if you turn on the vent when the light is on (or viceversa the command sent to turn on the lamp when the vent is on).
Not sure if `DISABLE` means "turn off" or "ignore the command".

Thanks.

2023-08-16 01:15 UTC, zimmra commented
## Light Turned On (VENT ALREADY ON)

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 1,
            "mwoLampOnOff": "ENABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 1
        }
    },
    "dataValue": null
}
```

## Vent Turned On (LIGHT ALREADY ON)

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 1,
            "mwoLampOnOff": "ENABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 1
        }
    },
    "dataValue": null
}
```

## Vent turned off, light left on

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 1,
            "mwoLampOnOff": "ENABLE",
            "mwoVentOnOff": "DISABLE",
            "mwoVentSpeedLevel": 0
        }
    },
    "dataValue": null
}
```

## Light turned off, vent left on

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 0,
            "mwoLampOnOff": "DISABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 1
        }
    },
    "dataValue": null
}
```

2023-08-16 10:52 UTC, ollo69 commented
Ok, now it should be ready for merge, just wait for final test.
I also restored the `set_time` service because now are clear required parameters.

2023-08-16 16:44 UTC, zimmra commented
> just wait for final test.

### Light (select) entity turns light on/off, but always goes to low

- WHEN SET TO HIGH IN LG APP - Home Assistant updates the select entity state **correctly**
- WHEN SET TO HIGH IN HOME ASSISTANT - Home Assistant initially shows the state as the selected state, but it is actually set to `LOW` in reality/the LG app. This eventually updates to `LOW` in Home Assistant

### Vent Speed (select) entity turns vent on/off, but always goes to high 

- WHEN SET TO ANYTHING OTHER THAN HIGH IN LG APP - Home Assistant updates the select entity state **correctly**
- WHEN SET TO ANYTHING OTHER THAN HIGH IN HOME ASSISTANT - Home Assistant initially shows the state as the selected state, but it is actually set to `HIGH` in reality/the LG app. This eventually updates to `HIGH` in Home Assistant

<details>
**<summary>Additional Control Commands (Expandable)</summary>**

All control commands sent to `https://aic-service.lgthinq.com:46030/v1/service/devices/{redacted}/control-sync`

## Fan to Low 

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 0,
            "mwoLampOnOff": "DISABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 1
        }
    },
    "dataValue": null
}
```

## Fan to Mid

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 0,
            "mwoLampOnOff": "DISABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 2
        }
    },
    "dataValue": null
}
```

## Fan to High

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 0,
            "mwoLampOnOff": "DISABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 3
        }
    },
    "dataValue": null
}
```

## Fan to Turbo

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 0,
            "mwoLampOnOff": "DISABLE",
            "mwoVentOnOff": "ENABLE",
            "mwoVentSpeedLevel": 4
        }
    },
    "dataValue": null
}
```

## Light to Low

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 1,
            "mwoLampOnOff": "ENABLE",
            "mwoVentOnOff": "DISABLE",
            "mwoVentSpeedLevel": 0
        }
    },
    "dataValue": null
}
```

## Light to High

```json
{
    "command": "Set",
    "ctrlKey": "setVentLampLevel",
    "dataGetList": null,
    "dataKey": null,
    "dataSetList": {
        "ovenState": {
            "cmdOptionContentsType": "REMOTE_VENT_LAMP",
            "cmdOptionDataLength": "REMOTE_VENT_LAMP",
            "mwoLampLevel": 2,
            "mwoLampOnOff": "ENABLE",
            "mwoVentOnOff": "DISABLE",
            "mwoVentSpeedLevel": 0
        }
    },
    "dataValue": null
}
```

</details>

2023-08-16 17:43 UTC, ollo69 commented
> Light (select) entity turns light on/off, but always goes to low

Probably level must be provided as `int` and not as `string`. Please try again.

Thanks

2023-08-16 17:49 UTC, ollo69 commented
> If you ever need other people to get info from a mitm setup, I logged what I did for my own future reference [here](https://github.com/zimmra/frida-rootbypass-and-sslunpinning-lg-thinq), feel free to point people to it if you need API info in the future. All they need is a WSA-capable Windows 11 PC, and know how to use terminal

This is a great info and would probably help a lot for future implementation in this integration. If is ok for you I would add this information in read-me (or if you prefer you can create a PR for this).

Thanks again.

2023-08-16 18:40 UTC, zimmra commented
>If is ok for you I would add this information in read-me (or if you prefer you can create a PR for this).

Like I said, glad to help! Feel free to use/modify/scrap https://github.com/ollo69/ha-smartthinq-sensors/pull/582 

>Probably level must be provided as int and not as string. Please try again.

That seems to have done it, all levels are properly controllable.

Everything _seems_ to be functioning as intended in this iteration

2023-08-16 18:52 UTC, merged

2023-08-19 04:10 UTC, trentjw commented
Tried this out the light control works and is controllable but the Fan shows unavailable and does not work

2023-08-19 13:17 UTC, ollo69 commented
@trentjw ,

this PR is closed and merged and new integration release is available, so please do not post here but open a dedicated issue providing detail and attaching integration diagnostic.

Thanks👍