Fix for HomeKit fan modes (issue #563)
ollo69/ha-smartthinq-sensors pull request #704
Opened 2024-02-20 14:55 UTC by diegocjorge

All credits to @kparmun for the fix:

https://github.com/ollo69/ha-smartthinq-sensors/issues/563#issuecomment-1612297396

2024-02-20 18:28 UTC, ollo69 commented
It doesn't look really good alter an enum using in some cases lower case and in other upper case. If the problem is that HomeKit just support lower case options, the change should be implemented in the methods `fan_speeds`, `fan_speed` and `set_fan_speed` to convert the values in lower case.

2024-02-20 20:06 UTC, diegocjorge commented
Hey @ollo69, hope it's better now. I'm not much of a coder.

2024-02-22 00:18 UTC, ollo69 commented on custom_components/smartthinq_sensors/wideq/devices/ac.py
>          speed_value = self.model_info.enum_value(keys[2], ACFanSpeed[speed].value)
```suggestion
        keys = self._get_cmd_keys(CMD_STATE_WIND_STRENGTH)
        # Convert upper() necessary for HomeKit compatibility
        speed_value = self.model_info.enum_value(keys[2], ACFanSpeed[speed.upper()].value)
```

2024-02-22 00:21 UTC, ollo69 requested changes
Please take a look to suggested changes and fix black formatting

2024-02-22 07:40 UTC, ollo69 commented on custom_components/smartthinq_sensors/wideq/devices/ac.py
>          if speed not in self.fan_speeds:
```suggestion
        if speed.lower() not in self.fan_speeds:
```

2024-02-22 07:42 UTC, ollo69 commented on custom_components/smartthinq_sensors/wideq/devices/ac.py
>          if speed not in self.fan_speeds:
Probably is better to also put here a lower() to not break existing configured service calls

2024-02-23 15:19 UTC, diegocjorge commented
I committed the changes you recommended

2024-02-23 23:42 UTC, ollo69 commented
Not sure this is the right solution. Probably fan modes should be mapped with [HA modes](https://developers.home-assistant.io/docs/core/entity/climate#fan-modes).
Let me think about this.

2024-02-24 00:54 UTC, ollo69 approved these changes

2024-02-24 00:59 UTC, merged